### =====================================
### RF01 - Buscar todos os produtos
### =====================================

GET http://localhost:3000/produtos

###

### =====================================
### RF02 - Buscar produto por ID
### =====================================

GET http://localhost:3000/produtos/11

###

### =====================================
### RF03 - Cadastrar produto
### =====================================

POST http://localhost:3000/produtos
Content-Type: application/json

{
    "nome": "Maquita",
    "preco": 150
}

###

### =====================================
### RF04 - Atualizar produto
### =====================================

PUT http://localhost:3000/produtos/11
Content-Type: application/json

{
    "nome": "Maquita",
    "preco": 180
}

###

### =====================================
### RF05 - Excluir produto
### =====================================

DELETE http://localhost:3000/produtos/11